version: '3.1'

services:

  node:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    
  react:
    build:
      args:
        - NODE_ENV=development
    depends_on:
      - node

  postgres:
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
