version: '3.1'

services:

  node:
    build:
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  react:
    build:
      args:
        - NODE_ENV=test
    depends_on:
      - node
  
  postgres:
    volumes:
      - ./database/postgres_test:/docker-entrypoint-initdb.d
      - ./database/postgres_test/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_test
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
