version: "3.1"

services:
  backend:
    container_name: backend
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./backend/package.json:/home/node/app/package.json
      - ./backend/package-lock.json:/home/node/app/package-lock.json
      - /home/node/app/node_modules
    healthcheck:
      disable: true
    depends_on:
      - mysql

  frontend:
    container_name: frontend
    ports:
      - "80:8080"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/home/node/app
      - ./frontend/package.json:/home/node/app/package.json
      - ./frontend/package-lock.json:/home/node/app/package-lock.json
      - /home/node/app/node_modules
    healthcheck:
      disable: true
    depends_on:
      - backend

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./backend/src/db/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
