version: "3.1"

services:
  backend:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres

  frontend:
    build:
      args:
        - NODE_ENV=development

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram_dev
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
