version: "3.1"

services:
  backend:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - DB_NAME=instagram_dev
      - DB_USER=mysql
      - DB_PASSWORD=myqsl
      - DB_HOST=mysql

  frontend:
    build:
      args:
        - NODE_ENV=development

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=instagram_dev
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
